#name: Daily render ping

on:
  schedule:
    - cron: '0 */2 * * *'   # Runs every 2 hours
  workflow_dispatch:        # Allows manual triggering

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Run cURL on Website
        run: curl -I https://twynk.onrender.com/
